[package]
name = "zuo_cheng_yun"
version = "0.1.0"
authors = ["steepcurve <steepcurve@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
assert_approx_eq = "1.1.0"
